spring:
  application:
    name: interp.log.api
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(WBA6GnCCnGXAn3o+OqObJAm71g+WitNmuzjAOkPup4IrWCgBYKuC8SOjYzeHHcbYir5ZJddp2JNtry6+BWJxXM3HN50FvOzYigeywwgdk/m359oYf6o1NMFqJoS3eYCoQ/62izf/aOI6JLeodQagDtdUhv6Sze8srnqSnXeQpgj+hngwRc35nam0aqQglfor)
    username: ENC(rkkeyGWr8WMOSoCGDC1neA==)
    password: ENC(v7TDxb3/HBUjTPtQHTfxww==)
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
  sql:
    init:
      platform: mariadb
      mode: always
      schema-locations: classpath:/schema.sql
      data-locations: classpath:/data.sql
  profiles:
    include: jwt

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: devgrr
    algorithm: PBEWithMD5AndDES

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    net.devgrr.interp.log.api: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
    doc-expansion: none

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
server:
  port: 8081
  error:
    include-stacktrace: always